FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
    apt-get install -y \
        netcat-openbsd \
        gettext \
        httpie && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    pip install flask

RUN mkdir /code
WORKDIR /code
COPY ./server.py .

ENTRYPOINT ["python","./server.py"]